{"uuid": "d187a330-43d9-4981-9fa4-c48cda628bde", "children": ["e0b349fc-f140-47d2-8d79-76b17bee78ba"], "befores": [{"name": "remote_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=103.0.5060.114)\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x0062D953+2414931]\n\tOrdinal0 [0x005BF5E1+1963489]\n\tOrdinal0 [0x004AC6B8+837304]\n\tOrdinal0 [0x00494120+737568]\n\tOrdinal0 [0x004F6E29+1142313]\n\tOrdinal0 [0x00503FB2+1195954]\n\tOrdinal0 [0x004F42B6+1131190]\n\tOrdinal0 [0x004CE860+976992]\n\tOrdinal0 [0x004CF756+980822]\n\tGetHandleVerifier [0x0089CC62+2510274]\n\tGetHandleVerifier [0x0088F760+2455744]\n\tGetHandleVerifier [0x006BEABA+551962]\n\tGetHandleVerifier [0x006BD916+547446]\n\tOrdinal0 [0x005C5F3B+1990459]\n\tOrdinal0 [0x005CA898+2009240]\n\tOrdinal0 [0x005CA985+2009477]\n\tOrdinal0 [0x005D3AD1+2046673]\n\tBaseThreadInitThunk [0x75F2FA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77AB7A9E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77AB7A6E+238]\n\n", "trace": "  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\工具\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\工具\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\selenium_compass\\cases\\test_case_pytest.py\", line 38, in remote_driver\n    lg.login()\n  File \"D:\\selenium_compass\\pages\\login_page.py\", line 14, in login\n    self.input(self.username,13761362771)\n  File \"D:\\selenium_compass\\base\\base_page.py\", line 39, in input\n    self.locator(loc).send_keys(txt)\n  File \"D:\\selenium_compass\\base\\base_page.py\", line 34, in locator\n    return self.driver.find_element(*loc)\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1251, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\工具\\python\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1657706710106, "stop": 1657706785303}], "start": 1657706710106, "stop": 1657706785472}