{"name": "发起异常报备", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'", "trace": "self = <pages.workplace_page.recruit_page.recruit_page.Recruit object at 0x04A1BB50>\nloc = ('xpath', \"//*[@class='ant-message-custom-content ant-message-success']/span\")\nexpect = '上传成功！1'\n\n    def assert_text(self,loc,expect):\n        logging.info('断言有无{}'.format(expect))\n        try:\n>           assert expect in self.locator(loc).text\nE           AssertionError\n\nbase\\base_page.py:48: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nremote_driver = <selenium.webdriver.remote.webdriver.WebDriver (session=\"d5c627d8c3acda05933a45b568ff9049\")>\n\n    @pytest.mark.run(order=1)\n    @pytest.mark.workspace1\n    @allure.feature(\"异常报备\")\n    @allure.story(\"发起异常报备\")\n    @allure.title(\"发起异常报备\")\n    def test_01(remote_driver):\n        wp=WorkPlace(remote_driver)\n        re = Recruit(remote_driver)\n        wp.open_recruit()\n>       re.abnormal_report(1)\n\ncases\\test_case_pytest.py:77: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\workplace_page\\recruit_page\\recruit_page.py:92: in abnormal_report\n    self.assert_text(self.tips,'上传成功！1')\nbase\\base_page.py:54: in assert_text\n    allure.attach(self.screen_short())\nd:\\工具\\python\\lib\\site-packages\\allure_commons\\_allure.py:179: in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\nd:\\工具\\python\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nd:\\工具\\python\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nd:\\工具\\python\\lib\\site-packages\\allure_pytest\\listener.py:222: in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\nd:\\工具\\python\\lib\\site-packages\\allure_commons\\reporter.py:119: in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\nd:\\工具\\python\\lib\\site-packages\\pluggy\\_hooks.py:265: in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\nd:\\工具\\python\\lib\\site-packages\\pluggy\\_manager.py:80: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <allure_commons.logger.AllureFileLogger object at 0x042184D8>\nbody = None\nfile_name = '8073c513-c950-419b-975b-ff19dbe0cb20-attachment.attach'\n\n    @hookimpl\n    def report_attached_data(self, body, file_name):\n        destination = os.path.join(self._report_dir, file_name)\n        with open(destination, 'wb') as attached_file:\n            if isinstance(body, text_type):\n                attached_file.write(body.encode('utf-8'))\n            else:\n>               attached_file.write(body)\nE               TypeError: a bytes-like object is required, not 'NoneType'\n\nd:\\工具\\python\\lib\\site-packages\\allure_commons\\logger.py:62: TypeError"}, "description": "招聘管理", "steps": [{"name": "招聘中心", "status": "passed", "start": 1657610275138, "stop": 1657610277704}, {"name": "我要报备", "status": "passed", "start": 1657610277704, "stop": 1657610278817}, {"name": "选择异常报备", "status": "passed", "start": 1657610278817, "stop": 1657610280635}, {"name": "选择需求框", "status": "passed", "start": 1657610280635, "stop": 1657610281418}, {"name": "选择报备测试", "status": "passed", "start": 1657610281419, "stop": 1657610282249}, {"name": "下一步", "status": "passed", "start": 1657610282249, "stop": 1657610283170}, {"name": "执行脚本生成异常报备数据", "status": "passed", "start": 1657610283170, "stop": 1657610284421}, {"name": "上传文件", "status": "passed", "start": 1657610284421, "stop": 1657610286331}, {"name": "下一步", "status": "passed", "start": 1657610286331, "stop": 1657610287065}, {"name": "断言", "status": "broken", "statusDetails": {"message": "TypeError: a bytes-like object is required, not 'NoneType'\n", "trace": "  File \"D:\\selenium_compass\\pages\\workplace_page\\recruit_page\\recruit_page.py\", line 92, in abnormal_report\n    self.assert_text(self.tips,'上传成功！1')\n  File \"D:\\selenium_compass\\base\\base_page.py\", line 54, in assert_text\n    allure.attach(self.screen_short())\n  File \"d:\\工具\\python\\lib\\site-packages\\allure_commons\\_allure.py\", line 179, in __call__\n    plugin_manager.hook.attach_data(body=body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\工具\\python\\lib\\site-packages\\allure_pytest\\listener.py\", line 222, in attach_data\n    self.allure_logger.attach_data(uuid4(), body, name=name, attachment_type=attachment_type, extension=extension)\n  File \"d:\\工具\\python\\lib\\site-packages\\allure_commons\\reporter.py\", line 119, in attach_data\n    plugin_manager.hook.report_attached_data(body=body, file_name=file_name)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_hooks.py\", line 265, in __call__\n    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_manager.py\", line 80, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 60, in _multicall\n    return outcome.get_result()\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_result.py\", line 60, in get_result\n    raise ex[1].with_traceback(ex[2])\n  File \"d:\\工具\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\工具\\python\\lib\\site-packages\\allure_commons\\logger.py\", line 62, in report_attached_data\n    attached_file.write(body)\n"}, "attachments": [{"source": "8073c513-c950-419b-975b-ff19dbe0cb20-attachment.attach"}], "start": 1657610287065, "stop": 1657610288846}], "attachments": [{"name": "log", "source": "907e0ebb-8955-4b60-a4b7-bf4064307a81-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "cede504d-6687-4ebc-91bb-12a5a2753d46-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "2add1c13-6526-4c10-941f-13ff4f440b70-attachment.txt", "type": "text/plain"}], "start": 1657610272231, "stop": 1657610288859, "uuid": "f2739d45-4d62-4ad3-a9bb-95ff205bcedd", "historyId": "2a355f25c142cade234abd3e04252c15", "testCaseId": "78a5ae7fc328611cd629e489cdd4c000", "fullName": "cases.test_case_pytest#test_01", "labels": [{"name": "feature", "value": "异常报备"}, {"name": "story", "value": "发起异常报备"}, {"name": "tag", "value": "run(order=1)"}, {"name": "tag", "value": "workspace1"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_case_pytest"}, {"name": "host", "value": "LAPTOP-5D6NI12E"}, {"name": "thread", "value": "29836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_case_pytest"}]}